# Generated by Django 4.0.6 on 2023-09-19 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finbaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=68, null=True)),
                ('percentage_return', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('maximum_amount', models.FloatField(default=0, null=True)),
                ('minimum_amount', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mimimum_amount', models.FloatField(blank=True, default=0, null=True)),
                ('maximum_amount', models.FloatField(blank=True, default=0, null=True)),
                ('return_of_investment', models.CharField(blank=True, max_length=5000, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_agenda', models.CharField(blank=True, default='Live Video', max_length=68, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='profile_pic',
            new_name='ID_CARD',
        ),
        migrations.AddField(
            model_name='client',
            name='Date_of_birth',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_duration',
            field=models.FloatField(blank=True, default=180, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('RATHER NOT SAY', 'RATHER NOT SAY')], default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_income',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_age',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_fullname',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('RATHER NOT SAY', 'RATHER NOT SAY')], default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_home_address',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_phonenumber',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reason_for_investing',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='relationship_status_with_next_of_kin',
            field=models.CharField(blank=True, choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SIBLING', 'SIBLING'), ('SPOUSE', 'SPOUSE'), ('OTHERS', 'OTHERS')], default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment_id',
            name='contract_duration',
            field=models.FloatField(blank=True, default=180, null=True),
        ),
        migrations.AddField(
            model_name='payment_id',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message_body', models.TextField(blank=True, max_length=1500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finbaapp.client')),
            ],
        ),
    ]
